replicaCount: 2

image:
  repository: ""
  tag: ""

service:
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: api.gkiladze.space
  path: /
  pathType: Prefix

tls:
  enabled: true
  issuerName: letsencrypt-prod
  issuerPrivateKeySecretName: letsencrypt-prod-account-key
  email: ""
  acmeServer: https://acme-v02.api.letsencrypt.org/directory
  secretName: azproj-api-tls

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

probes:
  readinessPath: /healthz
  livenessPath: /healthz
  port: 8080
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3
  
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
  
appConfig:
  environment: "prod"
  marketplaceName: "Cloud-Native Marketplace"