image:
  repository: ""
  tag: ""
replicaCount: 1
service:
  port: 8080
ingress:
  enabled: true
  className: nginx
  host: ""
  path: /
  pathType: Prefix
tls:
  enabled: false
  issuerName: letsencrypt-staging
  issuerPrivateKeySecretName: letsencrypt-staging-account-key
  email: ""
  acmeServer: https://acme-staging-v02.api.letsencrypt.org/directory
  secretName: azproj-api-tls