name: terraform-apply

on:
  push:
    branches: ["main"]
    paths:
      - "infra/**"

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash
    working-directory: infra/live/prod

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4

      - name: Show Azure IDs (debug)
        run: |
          echo "AZURE_TENANT_ID=${{ vars.AZURE_TENANT_ID }}"
          echo "AZURE_SUBSCRIPTION_ID=${{ vars.AZURE_SUBSCRIPTION_ID }}"
          echo "AZURE_CLIENT_ID_APPLY=${{ vars.AZURE_CLIENT_ID_APPLY }}"

      - uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID_APPLY }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v3

      - name: terraform init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ vars.TFSTATE_RG }}" \
            -backend-config="storage_account_name=${{ vars.TFSTATE_SA }}" \
            -backend-config="container_name=${{ vars.TFSTATE_CONTAINER }}" \
            -backend-config="key=prod.terraform.tfstate"

      - name: terraform apply
        run: terraform apply -auto-approve
